# Generated by Django 5.1 on 2024-09-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="autor",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
